language: c

compiler:
  - clang
  - gcc

env:
  # Mainline
  - NGINX=1.11.3
  - NGINX=1.11.3  DYNAMIC=1
  # Stable
  - NGINX=1.10.1
  - NGINX=1.10.1  DYNAMIC=1
  # Other configurations
  - NGINX=1.9.15
  - NGINX=1.9.15  DYNAMIC=1
  - NGINX=1.8.1
  # Also, the oldest supported version
  # TODO: Fails building because it won't find IOV_MAX from header.
  #- NGINX=0.7.69

sudo: false

addons:
  apt:
    packages:
      - libpcre3-dev
      - libssl-dev

cache: ccache

script:
  - wget -O - http://nginx.org/download/nginx-${NGINX}.tar.gz | tar -xzf -
  - rm -rf prefix/
  - ( cd nginx-${NGINX} && ./configure --add-${DYNAMIC:+dynamic-}module=.. --with-http_addition_module --prefix="$(pwd)/../prefix" && make install )
  - ./t/run "$(pwd)/prefix" ${DYNAMIC}
